# Generated by Django 5.0.2 on 2025-06-05 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stopage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=10, unique=True)),
                (
                    "end_stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_end",
                        to="app.stopage",
                    ),
                ),
                (
                    "start_stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_start",
                        to="app.stopage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteStopage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.route"
                    ),
                ),
                (
                    "stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.stopage"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("route", "order")},
            },
        ),
    ]
