# Generated by Django 5.0.2 on 2025-06-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_stopage_route_routestopage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField()),
                ("is_ended", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        limit_choices_to={"role": "bus"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.route"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                (
                    "stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.stopage"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival_time"],
            },
        ),
    ]
