# Generated by Django 5.0.2 on 2025-06-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_trip_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=100, unique=True)),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="routestopage",
            name="distance_from_last_stopage",
            field=models.FloatField(
                default=10, help_text="Distance (in km) from the previous stopage"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_on", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.card"
                    ),
                ),
                (
                    "end_stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_end",
                        to="app.stopage",
                    ),
                ),
                (
                    "start_stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_start",
                        to="app.stopage",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.trip"
                    ),
                ),
            ],
        ),
    ]
