# Generated by Django 5.0.2 on 2025-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_card_routestopage_distance_from_last_stopage_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="issued_on",
        ),
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
