# Generated by Django 5.0.2 on 2025-06-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_ticket_issued_on_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="end_stopage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_end",
                to="app.stopage",
            ),
        ),
    ]
