# Generated by Django 5.0.2 on 2025-06-22 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_ticket_end_stopage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "road_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ImgNow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("value", models.IntegerField()),
                (
                    "stopage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.stopage"
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.road"
                    ),
                ),
            ],
        ),
    ]
