# Generated by Django 5.0.2 on 2025-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_road_imgnow"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="available_seats",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_seats",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
