# Generated by Django 5.0.2 on 2025-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_trip_available_seats_trip_total_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
