# Generated by Django 5.0.2 on 2025-06-28 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_trip_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        limit_choices_to={"role": "Bus"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "Owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_buses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "bus")},
            },
        ),
    ]
