# Generated by Django 5.0.2 on 2025-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
