# Generated by Django 5.0.2 on 2025-09-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_schedule_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='taka',
            field=models.FloatField(default=0),
        ),
    ]
